### ISSUE TITLE
Replit counterpart

### ISSUE THREAD

**Issue by sc-lacanlale** [n4ze3m/shotty-fun#2]
can you by chance recreate this in replit? all my attempts to do so has failed and won't run.
Thank you

**Comment by n4ze3m** [comment]
Hey, in order to work, you need OpenAI , Fireworks and PEXELS  API keys, as well as a PostgreSQL database. Whisper and TTS will be using this timestamp API (https://github.com/n4ze3m/timetamp-whisper-api). Also, my Discord username is n4ze3m

**Comment by sc-lacanlale** [comment]
added you
